package org.project.carsharingapp.security;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.project.carsharingapp.util.TestDataHelper.createTestCustomer;

import io.jsonwebtoken.JwtException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.project.carsharingapp.model.user.User;
import org.springframework.test.util.ReflectionTestUtils;

public class JwtUtilTest {

    private final static User TEST_CUSTOMER = createTestCustomer();

    private JwtUtil jwtUtil;

    @BeforeEach
    void setJwtUtil() {
        jwtUtil = new JwtUtil();
        ReflectionTestUtils.setField(jwtUtil, "secret",
            "gRE4BURpoQU1A8yJ3qodGWqe+jcHsO0Ml4iHYhjIqUE=");
        ReflectionTestUtils.setField(jwtUtil, "expiration", 3600000);
    }

    @Test
    @DisplayName("""
        generateToken method with valid UserDetails
        should return non-null, non-blank token
        """)
    void generateToken_WithValidUserDetails_ShouldReturnToken() {
        // When
        String actual = jwtUtil.generateToken(TEST_CUSTOMER);

        // Then
        assertThat(actual).isNotNull().isNotBlank();
    }

    @Test
    @DisplayName("""
        getUsername method with token generated by generateToken
        should return original username
    """)
    void getUsername_WithValidToken_ShouldReturnOriginalUsername() {
        // Given
        String token = jwtUtil.generateToken(TEST_CUSTOMER);

        // When
        String actual = jwtUtil.getUsername(token);

        // Then
        assertThat(actual).isEqualTo(TEST_CUSTOMER.getUsername());
    }

    @Test
    @DisplayName("""
        getUsername method with expired token
        should throw JwtException
        """)
    void getUsername_WithExpiredToken_ShouldThrowJwtException() throws InterruptedException {
        // Given
        ReflectionTestUtils.setField(jwtUtil, "expiration", 1);
        String expiredToken = jwtUtil.generateToken(TEST_CUSTOMER);

        // When & Then
        Thread.sleep(10);
        assertThatThrownBy(() -> jwtUtil.getUsername(expiredToken))
            .isInstanceOf(JwtException.class);
    }

    @Test
    @DisplayName("""
        getUsername method with not Jwt token format
        should throw JwtException
        """)
    void getUsername_WithWrongTokenFormat_ShouldThrowJwtException() {
        // Given
        String invalidToken = "not jwt format token";

        // When & Then
        assertThatThrownBy(() -> jwtUtil.getUsername(invalidToken))
            .isInstanceOf(JwtException.class);
    }

    @Test
    @DisplayName("""
        isValidToken method with valid token
        should return boolean true
        """)
    void isValidToken_WithValidToken_ShouldReturnBooleanTrue() {
        // Given
        String token = jwtUtil.generateToken(TEST_CUSTOMER);

        // When
        boolean actual = jwtUtil.isValidToken(token);

        // Then
        assertThat(actual).isTrue();
    }

    @Test
    @DisplayName("""
        isValidToken method with expired token
        should return boolean false
        """)
    void isValidToken_WithExpiredToken_ShouldReturnBooleanFalse() throws InterruptedException {
        // Given
        ReflectionTestUtils.setField(jwtUtil, "expiration", 1);
        String expiredToken = jwtUtil.generateToken(TEST_CUSTOMER);

        // When
        Thread.sleep(10);
        boolean actual = jwtUtil.isValidToken(expiredToken);

        // Then
        assertThat(actual).isFalse();
    }

    @Test
    @DisplayName("""
        isValidToken method with not Jwt format token
        should return boolean false
        """)
    void isValidToken_WithWrongTokenFormat_ShouldReturnBooleanFalse() {
        // Given
        String invalidToken = "not jwt format token";

        // When
        boolean actual = jwtUtil.isValidToken(invalidToken);

        // Then
        assertThat(actual).isFalse();
    }

}
