spring.application.name=CarSharingApp
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.url=jdbc:postgresql://db:${POSTGRES_DOCKER_PORT}/${POSTGRES_DB}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-on-view=false

server.servlet.context-path=/api

app.base-url=${APP_BASE_URL:http://localhost:8080}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.chat-id=${TELEGRAM_CHAT_ID}
telegram.api-url=https://api.telegram.org

telegram.notifications.enabled=true

payments.stripe.secret-key=${STRIPE_SECRET_KEY}
payments.fine-multiplier=1.3
